In [52]:
#Importing libraries
import pandas as pd
from datasets import load_dataset

#loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

#Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [53]:
df_salary = df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

In [54]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy() #whenever you change something original df you have to copy this

def projected_salary(salary):
    return salary * 1.03 #3% inflation

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg','salary_year_inflated']] #comparing

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [55]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

df_salary[['salary_year_avg','salary_year_inflated']] #comparing  lambda

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [56]:
type(df['job_skills'][0])

float

In [58]:
import ast

# 1. Replace float NaNs with a stringified empty list
df['job_skills'] = df['job_skills'].fillna("[]")

# 2. Convert all rows safely
df['job_skills'] = df['job_skills'].apply(ast.literal_eval)

## Calculate the projected salary next year
- Senior roles assume 5%
- Other roles 3%
Senior roles assume 5%
other roles 3%